### ISSUE TITLE
Proxy status Problem

### ISSUE THREAD

**Issue by Madraka** [lyoshenka/cloudflare-ddns#10]
edit proxy status. allways close default

**Comment by schliflo** [comment]
Please elaborate on the exact problem you have:

- What kind of error do you get? 
- What does not work for you?
- What have you tried to fix it so far?

**Comment by Madraka** [comment]
my problem update dns. Proxy cloudflare closing after update dns. 
I want to keep it open cloudflare proxied. 

it would be great if an arrangement was made for it.

**Comment by schliflo** [comment]
I've opened a PR that adds support for this (and other things I had in my fork): #11

**Comment by Madraka** [comment]
> I've opened a PR that adds support for this (and other things I had in my fork): #11

you are really great, thank you very much
